// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/api/proto/match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchEmpty) Reset() {
	*x = MatchEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEmpty) ProtoMessage() {}

func (x *MatchEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEmpty.ProtoReflect.Descriptor instead.
func (*MatchEmpty) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{0}
}

type NextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SphereID int64 `protobuf:"varint,2,opt,name=sphereID,proto3" json:"sphereID,omitempty"`
}

func (x *NextRequest) Reset() {
	*x = NextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRequest) ProtoMessage() {}

func (x *NextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRequest.ProtoReflect.Descriptor instead.
func (*NextRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{1}
}

func (x *NextRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *NextRequest) GetSphereID() int64 {
	if x != nil {
		return x.SphereID
	}
	return 0
}

type NextReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextUserID int64 `protobuf:"varint,1,opt,name=nextUserID,proto3" json:"nextUserID,omitempty"`
}

func (x *NextReply) Reset() {
	*x = NextReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextReply) ProtoMessage() {}

func (x *NextReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextReply.ProtoReflect.Descriptor instead.
func (*NextReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{2}
}

func (x *NextReply) GetNextUserID() int64 {
	if x != nil {
		return x.NextUserID
	}
	return 0
}

type UpdateRecommendationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SphereID int64 `protobuf:"varint,2,opt,name=sphereID,proto3" json:"sphereID,omitempty"`
}

func (x *UpdateRecommendationsRequest) Reset() {
	*x = UpdateRecommendationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecommendationsRequest) ProtoMessage() {}

func (x *UpdateRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRecommendationsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateRecommendationsRequest) GetSphereID() int64 {
	if x != nil {
		return x.SphereID
	}
	return 0
}

var File_pkg_api_proto_match_proto protoreflect.FileDescriptor

var file_pkg_api_proto_match_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x41, 0x0a, 0x0b, 0x4e, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72, 0x65, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x09,
	0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x78,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e,
	0x65, 0x78, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x52, 0x0a, 0x1c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72, 0x65, 0x49, 0x44, 0x32, 0x72, 0x0a,
	0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x22, 0x0a, 0x04, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x0c,
	0x2e, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x4e,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_proto_match_proto_rawDescOnce sync.Once
	file_pkg_api_proto_match_proto_rawDescData = file_pkg_api_proto_match_proto_rawDesc
)

func file_pkg_api_proto_match_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_match_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_proto_match_proto_rawDescData)
	})
	return file_pkg_api_proto_match_proto_rawDescData
}

var file_pkg_api_proto_match_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_proto_match_proto_goTypes = []interface{}{
	(*MatchEmpty)(nil),                   // 0: MatchEmpty
	(*NextRequest)(nil),                  // 1: NextRequest
	(*NextReply)(nil),                    // 2: NextReply
	(*UpdateRecommendationsRequest)(nil), // 3: UpdateRecommendationsRequest
}
var file_pkg_api_proto_match_proto_depIdxs = []int32{
	1, // 0: Match.Next:input_type -> NextRequest
	3, // 1: Match.UpdateRecommendations:input_type -> UpdateRecommendationsRequest
	2, // 2: Match.Next:output_type -> NextReply
	0, // 3: Match.UpdateRecommendations:output_type -> MatchEmpty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_match_proto_init() }
func file_pkg_api_proto_match_proto_init() {
	if File_pkg_api_proto_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_proto_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_proto_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_proto_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_proto_match_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRecommendationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_proto_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_match_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_match_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_match_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_match_proto = out.File
	file_pkg_api_proto_match_proto_rawDesc = nil
	file_pkg_api_proto_match_proto_goTypes = nil
	file_pkg_api_proto_match_proto_depIdxs = nil
}
