// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/api/proto/match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromID   int64 `protobuf:"varint,1,opt,name=fromID,proto3" json:"fromID,omitempty"`
	ToID     int64 `protobuf:"varint,2,opt,name=toID,proto3" json:"toID,omitempty"`
	SphereID int64 `protobuf:"varint,3,opt,name=sphereID,proto3" json:"sphereID,omitempty"`
	IsLike   bool  `protobuf:"varint,4,opt,name=isLike,proto3" json:"isLike,omitempty"`
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetFromID() int64 {
	if x != nil {
		return x.FromID
	}
	return 0
}

func (x *MatchRequest) GetToID() int64 {
	if x != nil {
		return x.ToID
	}
	return 0
}

func (x *MatchRequest) GetSphereID() int64 {
	if x != nil {
		return x.SphereID
	}
	return 0
}

func (x *MatchRequest) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

type MatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReciprocated bool `protobuf:"varint,1,opt,name=isReciprocated,proto3" json:"isReciprocated,omitempty"`
}

func (x *MatchReply) Reset() {
	*x = MatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReply) ProtoMessage() {}

func (x *MatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReply.ProtoReflect.Descriptor instead.
func (*MatchReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_match_proto_rawDescGZIP(), []int{1}
}

func (x *MatchReply) GetIsReciprocated() bool {
	if x != nil {
		return x.IsReciprocated
	}
	return false
}

var File_pkg_api_proto_match_proto protoreflect.FileDescriptor

var file_pkg_api_proto_match_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0c, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x70, 0x68, 0x65, 0x72,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x73, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0e, 0x69, 0x73, 0x52, 0x65, 0x63, 0x69, 0x70, 0x72, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x32, 0x2e, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x25, 0x0a, 0x05, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x0d, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_proto_match_proto_rawDescOnce sync.Once
	file_pkg_api_proto_match_proto_rawDescData = file_pkg_api_proto_match_proto_rawDesc
)

func file_pkg_api_proto_match_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_match_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_proto_match_proto_rawDescData)
	})
	return file_pkg_api_proto_match_proto_rawDescData
}

var file_pkg_api_proto_match_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_proto_match_proto_goTypes = []interface{}{
	(*MatchRequest)(nil), // 0: MatchRequest
	(*MatchReply)(nil),   // 1: MatchReply
}
var file_pkg_api_proto_match_proto_depIdxs = []int32{
	0, // 0: Match.Match:input_type -> MatchRequest
	1, // 1: Match.Match:output_type -> MatchReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_match_proto_init() }
func file_pkg_api_proto_match_proto_init() {
	if File_pkg_api_proto_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_proto_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_proto_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_proto_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_match_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_match_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_match_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_match_proto = out.File
	file_pkg_api_proto_match_proto_rawDesc = nil
	file_pkg_api_proto_match_proto_goTypes = nil
	file_pkg_api_proto_match_proto_depIdxs = nil
}
