// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/api/proto/rengine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// REngineClient is the client API for REngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type REngineClient interface {
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error)
}

type rEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewREngineClient(cc grpc.ClientConnInterface) REngineClient {
	return &rEngineClient{cc}
}

func (c *rEngineClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error) {
	out := new(NextReply)
	err := c.cc.Invoke(ctx, "/REngine/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// REngineServer is the server API for REngine service.
// All implementations must embed UnimplementedREngineServer
// for forward compatibility
type REngineServer interface {
	Next(context.Context, *NextRequest) (*NextReply, error)
	mustEmbedUnimplementedREngineServer()
}

// UnimplementedREngineServer must be embedded to have forward compatible implementations.
type UnimplementedREngineServer struct {
}

func (UnimplementedREngineServer) Next(context.Context, *NextRequest) (*NextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedREngineServer) mustEmbedUnimplementedREngineServer() {}

// UnsafeREngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to REngineServer will
// result in compilation errors.
type UnsafeREngineServer interface {
	mustEmbedUnimplementedREngineServer()
}

func RegisterREngineServer(s grpc.ServiceRegistrar, srv REngineServer) {
	s.RegisterService(&REngine_ServiceDesc, srv)
}

func _REngine_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(REngineServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/REngine/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(REngineServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// REngine_ServiceDesc is the grpc.ServiceDesc for REngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var REngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "REngine",
	HandlerType: (*REngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _REngine_Next_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/rengine.proto",
}
